spring:
  redis:
    host: 192.168.48.129
    port: 6379
    jedis:
      pool:
        max-active: 20
    password: 123
  datasource:
    url: jdbc:mysql:///shop-project
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
dubbo:
  application:
    name: cart-service
  registry:
    protocol: zookeeper
    address: 192.168.48.129:2181
  protocol:
    port: 20117
  provider:
    timeout: 600
server:
  port: 8187

