spring:
  data:
    solr:
      host: http://192.168.48.129:8080/solr
  datasource:
    url: jdbc:mysql:///shop-project
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.48.129
    port: 5672
    username: dq
    password: 123
    virtual-host: /java1809
dubbo:
  application:
    name: search-service
  registry:
    protocol: zookeeper
    address: 192.168.48.129:2181
  protocol:
    port: 20004
server:
  port: 8082
