package com.dq.miaosha.entity;

import java.io.Serializable;
import java.util.Date;

public class TSeckill implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.id
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.product_id
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.count
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.start_time
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.end_time
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.status
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.price
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seckill.sale_price
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    private Long salePrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.id
     *
     * @return the value of t_seckill.id
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.id
     *
     * @param id the value for t_seckill.id
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.product_id
     *
     * @return the value of t_seckill.product_id
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.product_id
     *
     * @param productId the value for t_seckill.product_id
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.count
     *
     * @return the value of t_seckill.count
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.count
     *
     * @param count the value for t_seckill.count
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.start_time
     *
     * @return the value of t_seckill.start_time
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.start_time
     *
     * @param startTime the value for t_seckill.start_time
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.end_time
     *
     * @return the value of t_seckill.end_time
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.end_time
     *
     * @param endTime the value for t_seckill.end_time
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.status
     *
     * @return the value of t_seckill.status
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.status
     *
     * @param status the value for t_seckill.status
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.price
     *
     * @return the value of t_seckill.price
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.price
     *
     * @param price the value for t_seckill.price
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seckill.sale_price
     *
     * @return the value of t_seckill.sale_price
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    public Long getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seckill.sale_price
     *
     * @param salePrice the value for t_seckill.sale_price
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    public void setSalePrice(Long salePrice) {
        this.salePrice = salePrice;
    }
}