dubbo:
  application:
    name: background
  registry:
    protocol: zookeeper
    address: 192.168.48.129:2181
server:
  port: 9090
fdfs:
  so-timeout: 10000
  connect-timeout: 10000
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 10.36.8.8:22122
spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.48.129
    port: 5672
    username: dq
    password: 123
    virtual-host: /java1809
image:
  server: http://10.36.8.8/