dubbo:
  application:
    name: product-service
  registry:
    protocol: zookeeper
    address: 192.168.48.129:2181
  protocol:
    port: 20001
server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql:///shop-project
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.48.129
    port: 5672
    username: dq
    password: 123
    virtual-host: /java1809