package com.dq.miaosha.mapper;

import com.dq.miaosha.entity.TProduct;

public interface TProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    int insert(TProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    int insertSelective(TProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    TProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    int updateByPrimaryKeySelective(TProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    int updateByPrimaryKey(TProduct record);
}