package com.dq.miaosha.mapper;

import com.dq.miaosha.entity.TSeckill;

import java.util.List;

public interface TSeckillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    int insert(TSeckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    int insertSelective(TSeckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    TSeckill selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    int updateByPrimaryKeySelective(TSeckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_seckill
     *
     * @mbggenerated Fri Mar 29 17:35:56 CST 2019
     */
    int updateByPrimaryKey(TSeckill record);

    List<TSeckill> getCanStartSeckills();

    void updateSeckill(TSeckill seckill);

    List<TSeckill> getCanStopSeckills();
}